### ISSUE TITLE
Include further user metadata related to Linkedin, ResearchGate, ORCID, ResearchID

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/plat-serv-bvs#10]
Evaluate how to use related API in order to save more information into user profile.

**Comment by wilsonmoura** [comment]
Incluir curriculo Lattes (para pesquisadores no Brasil)

**Comment by wilsonmoura** [comment]
Verificar a boa prática utilizada para armazenamento deste tipo de dado.

**Comment by wilsonmoura** [comment]
Segue exemplos de boas práticas de armazenamento dos dados mencionados:

**LinkedIn**: www.linkedin.com/in/SLUG - ex. https://br.linkedin.com/in/marcos-luis-mori-a159758
**ResearchGate**: https://www.researchgate.net/profile/USERNAME - ex. https://www.researchgate.net/profile/Renato_Murasaki
**ORCID**: http://orcid.org/ORCID-ID - ex. http://orcid.org/0000-0002-4167-2079
**ResearcherID**: http://www.researcherid.com/rid/RESEARCHER-ID - ex. http://www.researcherid.com/rid/H-2749-2014
**Lattes**: http://buscatextual.cnpq.br/buscatextual/visualizacv.do?id=LATTES-ID - ex. http://buscatextual.cnpq.br/buscatextual/visualizacv.do?id=K4793246E6

Sobre as APIs relacionadas, somente o ORCID oferece esse recurso sem a necessidade de autenticação. Segue link da documentação da API e exemplo de uso:

**Documentação**: https://members.orcid.org/api/
**ORCID API**: https://pub.orcid.org/v1.2/ORCID-ID/RESOURCE - ex. https://pub.orcid.org/v1.2/0000-0002-4167-2079/orcid-bio
