### ISSUE TITLE
Deployment do SimilarDocs no ambiente de produção

### ISSUE THREAD

**Issue by wilsonmoura** [bireme/plat-serv-bvs#100]

**Comment by heitorbarbieri** [comment]
Serviço de Documentos Similares instalado no servidor de produção no endereço:

http://basalto01.bireme.br:8180/SDService

@wilsonmoura, por favor, verificar.

**Comment by wilsonmoura** [comment]
Serviço testado e funcionando bem no ambiente de produção.
