### ISSUE TITLE
Alterar estrutura da página de login

### ISSUE THREAD

**Issue by sousajul** [bireme/plat-serv-bvs#102]
Devido a rolagem de página ocasionada pela resolução de alguns computadores, alterar estrutura da página de login seguindo modelo do NCBI: https://www.ncbi.nlm.nih.gov/account/?back_url=https%3A%2F%2Fwww.ncbi.nlm.nih.gov%2Fpubmed%2F

Na caixa de login, incluir os seguintes textos que estão em vermelho na imagem:

![image](https://user-images.githubusercontent.com/13439949/28430602-8079ab8e-6d57-11e7-937d-ea1f0a313eb8.png)

**Comment by wilsonmoura** [comment]
@sousajul Os ajustes de layout na área de login foram realizados no ambiente de testes. Favor validar.

**Comment by sousajul** [comment]
Validado.
