### ISSUE TITLE
Alterar posição dos links no topo da página do item Visão Geral

### ISSUE THREAD

**Issue by sousajul** [bireme/plat-serv-bvs#103]
_Sugestão da Verônica:_
Na "visão geral", retirar os textos que aparecem abaixo dos números em Documentos Favoritos, Links Favoritos e Temas de Interesse e colocar o link de "ver todos" nos números.

![image](https://user-images.githubusercontent.com/13439949/28434998-c89c4bb4-6d67-11e7-99df-52a12d8f08a1.png).

**Comment by wilsonmoura** [comment]
Em vez de excluir os links mencionados, será adicionado link no número que indica o total dos respectivos serviços.

**Comment by wilsonmoura** [comment]
@sousajul Ajustes realizados no ambiente de testes. Favor validar.

**Comment by sousajul** [comment]
Validado.
