### ISSUE TITLE
Revisar navegação após usuário registrar-se no serviço por meio do link "Registrar-se"

### ISSUE THREAD

**Issue by sousajul** [bireme/plat-serv-bvs#105]
Após usuário se registra no serviço em "Registre-se", aparece a mensagem de usuário registrado com sucesso, mas se mantem na página de se registrar. 

- Ou o sistema direciona para a página inicial de login, ou  sistema já loga e cai na página de perfil para que o usuário complete os dados do perfil.

**Comment by wilsonmoura** [comment]
Ao submeter o formulário de cadastro de usuários, o mesmo deixará de ser exibido. Assim, a mensagem exibida ao usuário ganhará mais destaque.

**Comment by wilsonmoura** [comment]
@sousajul Os ajustes foram realizados. Favor validar.
