### ISSUE TITLE
Criar opção do usuário apagar sua conta no Minha BVS

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/plat-serv-bvs#123]
Esta opção deve eliminar toda a sua informação pessoal de cadastro e de uso dos serviços personalizados. Está presente na Política Geral de Privacidade da OPAS.

**Comment by wilsonmoura** [comment]
@renatomurasaki A opção para apagar a conta de usuário na Minha BVS foi implementada no ambiente de testes. Essa opção está disponível no menu Editar meu Perfil (veja na imagem):

![screenshot](https://user-images.githubusercontent.com/3779520/30916107-ee6a4188-a36e-11e7-94ea-2a506b972aa4.png)

No aguardo de sugestões do texto que será exibido ao usuário antes de confirmar a exclusão da conta.

**Comment by renatomurasaki** [comment]
@wilsonmoura sugiro o seguinte processo para confirmação do pedido de exclusão de usuário, baseando-se na experiência com o Facebook:

Sugestão de texto que deve aparecer antes das opções de motivo:

> Você solicitou a exclusão da sua conta nos Serviços Personalizados de Informação - Minha BVS. Ao excluí-la você perderá as informações relacionadas ao seu perfil, suas coleções de documentos, perfis de interesse e demais conteúdos da Minha BVS. Esta ação é irreversível.
> Se você tem certeza que quer excluir seu usuário, por favor, conte-nos rapidamente o motivo de deixar de utilizar o Minha BVS

Motivo da Exclusão (obrigatório)
- [ ] Eu não me sinto seguro no Minha BVS
- [ ] Eu não acho que o Minha BVS seja útil
- [ ] Minha conta foi invadida
- [ ] Não sei utilizar o Minha BVS
- [ ] Eu possuo outra conta no Minha BVS
- [ ] Recebo muitos e-mails do Minha BVS
- [ ] Tenho uma preocupação quanto à privacidade
- [ ] Outro

Campo aberto para "Dê mais detalhes sobre o motivo da sua saída" (opcional)

Ao clicar em prosseguir, mostrar outra página com a seguinte informação:

> Você está prestes a excluir permanentemente sua conta. Tem certeza? Em caso afirmativo, informe a sua senha e código de verificação de segurança.

O código de verificação de segurança é um código CAPTCHA
Enviar e-mail informando a exclusão.
