### ISSUE TITLE
Ao cadastrar o ORCID o mesmo não traz as publicações

### ISSUE THREAD

**Issue by sousajul** [bireme/plat-serv-bvs#129]
Foi incluído no campo ORCID o código 0000-0002-3373-9317 de Elisabeth Peres Biruel e o mesmo não recupera as publicações.

**Comment by renatomurasaki** [comment]
@sousajul Testei com o meu usuário ORCID e funcionou. As publicações da Beth estão configuradas para acesso público?

**Comment by wilsonmoura** [comment]
@sousajul Na Minha BVS, ao informar o ORCID, serão exibidos apenas os _works_ (publicações) do autor. Acessei o perfil da Elisabeth Biruel direto no site do ORCID. Vejam na imagem que nesse perfil é possível visualizar apenas informações pessoais, ou seja, não há publicações disponíveis.

![biruel](https://user-images.githubusercontent.com/3779520/29565346-f32583be-871b-11e7-93e4-50286d2d9e1b.png)

**Comment by sousajul** [comment]
Wilson, ontem quando acessamos o ORCID era apresentado sim as publicações, inclusive vi isso com o Vinicius. A Beth vai revisar o cadastro no ORCID para verificar se está publico.
Veja as publicações:

![image](https://user-images.githubusercontent.com/13439949/29570652-7205e2c6-872d-11e7-9732-8a086f87d038.png)

**Comment by wilsonmoura** [comment]
@sousajul O menu Educação exibido na imagem faz parte das informações pessoais do autor. As publicações, quando existentes e públicas, são apresentadas no menu Works (veja exemplo na imagem).

![wordks](https://user-images.githubusercontent.com/3779520/29584472-2cb12960-875a-11e7-9bdd-f60f1a2b9088.png)
