### ISSUE TITLE
Revisar comportamento do item Histórico de Buscas na BVS

### ISSUE THREAD

**Issue by sousajul** [bireme/plat-serv-bvs#130]
Ao realizar uma busca, o sistema salva o histórico, no entanto, ele duplica os históricos já realizados e ao clicar em "Exibir" abrem várias janelas, como se o sistema estivesse agrupando os históricos em um único link e ao clicar em um, abrem todos. Percebi que as páginas que abrem, são devido a "duplicação" no sistema
![image](https://user-images.githubusercontent.com/13439949/29534880-1fca07f2-868e-11e7-82b2-0528fc3642a3.png)

**Comment by wilsonmoura** [comment]
@sousajul A solução será implementada em #138
