### ISSUE TITLE
Não está salvando o tema de interesse

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/plat-serv-bvs#131]
Após informar as palavras-chave, o sistema lista os documentos relacionados, porém não salva o tema de interesse.

**Comment by renatomurasaki** [comment]
@wilsonmoura esse problema se reproduz com o usuário logado via Google. Usuário local (AD/LDAP) não reproduz o erro.

**Comment by sousajul** [comment]
Renato, apenas para verificação, ontem loguei com o Google e salvou dois temas. Acabei de acessar e criar um novo tema e salvou também.

**Comment by renatomurasaki** [comment]
Foi visto que este problema só se reproduz com um usuário específico. Aparentemente a causa é dos dados armazenados. Issue encerrado, sendo reaberto em caso de incidência com outro usuario.
