### ISSUE TITLE
Novo serviço: Resultados de Busca (RSS)

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/plat-serv-bvs#132]
Dar a possibilidade do usuário cadastrar diversos RSS provenientes da interface de busca da BVS. O botão RSS poderia dar a opção de acrescentar na Minha BVS, como serviço "Resultados de Pesquisa"

**Comment by renatomurasaki** [comment]
@sousajul o que você acha da possibilidade de desenvolver este novo serviço? Vale a pena?

**Comment by sousajul** [comment]
@renatomurasaki acredito que sim, este será um serviço bem interessante para o usuário. No entanto, para ter mais embasamento, conversei um pouco com a Beth que está mais próxima do usuário, e chegamos às seguintes justificativas que ao meu ver, reforçam a necessidade desse novo serviço:

- O usuário receberá no seu espaço (na Minha BVS) a atualização de documentos de acordo com uma estratégia pre definida e bem configurada, isso trará um resultado mais especifico que é diferente do serviço Temas de interesse;
- Pra quem trabalha com revisões sistemáticas, é fundamental receber atualizações de documentos a partir de uma estratégia bem definida;
- É fundamental não perder a estratégia que trouxe um bom resultado, receber atualizações de documentos então nem se fala;
- Muitas vezes nos cursos de pesquisa, as pessoas não sabem usar o RSS, tem dificuldade de utilizar os leitores de RSS;
- Mesmo para quem sabe utilizar os leitores, muitas vezes recebem por email, isso sobrecarregada a caixa de entrada, mistura os assuntos, ou em outros casos fazem um email especifico para isso;
- Ter esse serviço junto com os demais facilitará a vida do usuário já que esta é a BVS dele a "minha BVS" e não faz sentido ele ter que acessar outro local para visualizar os documentos.

Bom acho que é isso, caso necessário, podemos conversar mais sobre o tema ;-)

**Comment by sousajul** [comment]
@wilsonmoura conforme reunião com a participação da Elisabeth Biruel, seguem sugestões para este novo serviço:

**Sugestão do nome do novo serviço:** apenas RSS com o ícone do RSS.

**Funcionalidades:**
- Ter possibilidade de adicionar um documento da lista de RSS em "adicionar aos favoritos"
- Serviço de similares
- Adicionar o RSS a partir do resultado de pesquisa (iahx) do regional - nome da Label no iahx RSS e RSS minha BVS
- Editar um RSS
- Excluir um RSS
- Compartilhar um RSS (ver se será página publica igual compartilhar coleção ou o próprio link do RSS)
- Adicionar um novo RSS, incluindo uma URL pré definida (seguindo o padrão que já temos) - Meus RSS | Adicionar RSS.
![image](https://user-images.githubusercontent.com/13439949/34419576-c7c34cee-ebeb-11e7-812a-95c354fb7a4d.png)

**Sugestão:**
- Possibilidade de incluir um RSS de outras fontes de informação, ex: Pubmed, cochrane, SciELO, etc.

**Sugestão de arquitetura de página:**
- Página inicial
- Cada "quadrado" representa um RSS no qual o usuário pode editar o título do RSS e excluir este RSS
- Pode-se definir uma quantidade de RSS para aparecer na página inicial e incluir paginação
![image](https://user-images.githubusercontent.com/13439949/34419621-06118ef2-ebec-11e7-8162-601529083a1a.png)

- Ao clicar em cada quadrado mostra a página com a lista do resultado do RSS e as funcionalidades de "adicionar aos favoritos" e "similares" abaixo de cada documento.

![image](https://user-images.githubusercontent.com/13439949/34419707-7d265644-ebec-11e7-9780-4adc0a427b12.png).

**Comment by wilsonmoura** [comment]
Incluir serviço no tour da Minha BVS (#179).
