### ISSUE TITLE
Usuário local (AD/LDAP) antigo (renato.murasaki@bireme.org) não aparece na tabela users

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/plat-serv-bvs#133]
Mesmo assim consigo me logar e ver todos os meus documentos e perfis. Por não ter uma entrada na tabela users, não consigo ver o meu último login.

**Comment by wilsonmoura** [comment]
@renatomurasaki Fiz uma query pesquisando pelo userID renato.murasaki@bireme.org e encontrei esse usuário. Provavelmente você deve ter pesquisado pelo userEmail que, no caso desse usuário, está com o campo vazio. Segue a query:

SELECT * FROM users WHERE userID = 'renato.murasaki@bireme.org'

**Comment by renatomurasaki** [comment]
Está correto! Pode encerrar. Obrigado.

Renato
