### ISSUE TITLE
Documento adicionado a partir do Portal Regional não aparece na Minha BVS

### ISSUE THREAD

**Issue by heitorbarbieri** [bireme/plat-serv-bvs#140]
Quando o usuário clica no botão "Minha BVS" em um documento do portal (http://pesquisa.bvsalud.org/portal/) mas ainda não está logado na Minha BVS, ele é redirecionado em uma outra aba para o login da Minha BVS. Após se logar, ele retorna para a primeira página e clica novamente no botão para incluir o referido documento, mas o mesmo não é incluído a menos que o usuário faça antes um "refresh" da página do portal.

**Comment by wilsonmoura** [comment]
Testar ajuste validando o token gerado na Minha BVS.

**Comment by wilsonmoura** [comment]
Realizado em bireme/iahx-opac#21.
