### ISSUE TITLE
Verificar comportamento da funcionalidade Similares em Minhas publicações

### ISSUE THREAD

**Issue by sousajul** [bireme/plat-serv-bvs#147]
No serviço Minhas Publicações, ao clicar em Similares apresenta não apresenta os documentos de acordo com artigo que foi selecionado, está apresentando os similares dos outros serviços como Temas de interesse ou documentos favoritos (o último similares que foi clicado).

![image](https://user-images.githubusercontent.com/13439949/30038817-4109a44c-919f-11e7-903b-114cddd1e323.png)

**Comment by wilsonmoura** [comment]
@sousajul Fizemos alguns ajustes na recuperação dos similares em Minhas Publicações. Favor validar.

**Comment by renatomurasaki** [comment]
O erro acontecia qdo o documento recuperado via ORCID não tinha URL.

Renato

**Comment by sousajul** [comment]
Ok validado.
