### ISSUE TITLE
Sugestão do usuário

### ISSUE THREAD

**Issue by pintoros** [bireme/plat-serv-bvs#151]
En primer lugar felicidades por el desarrollo, nos parece un servicio muy útil. Tenemos una duda, ¿por qué cuando se trata de recursos de Internet (LIS) no lo lleva a "enlaces favoritos" de Mi BVS?, tampoco puedo moverlo de "documentos favoritos" a la carpeta "enlaces favoritos". Por lo que veo "enlaces favoritos" es para crear tu propio bookmark, pero creo que sería útil si se pudiera exportar a esta carpeta directamente cuando se trate de recursos de internet. Gracias.

Feedback 711 - bvs@isciii.es

**Comment by renatomurasaki** [comment]
@pintoros Para um usuário final que desconhece a diferença entre LIS e LILACS, por exemplo, adicionar um registro LIS diretamente nos Links Favoritos pode ser confuso, pois a ação esperada é inserir nos Documentos Favoritos. Você acha que seria suficiente informar na mensagem pop-up que o registro foi inserido nos Links Favotiros?

**Comment by wilsonmoura** [comment]
Dependência: bireme/iahx-opac#38
