### ISSUE TITLE
Alterar a funcionalidade de similares da Minha BVS para utilizar novo método de similaridade sem perfil

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/plat-serv-bvs#154]
@wilsonmoura verificar com @viniciusandrade a implementação feita no RedETSA.

**Comment by wilsonmoura** [comment]
@heitorbarbieri No aguardo das informações necessárias para implementar a chamada desse novo método de similaridade

**Comment by heitorbarbieri** [comment]
A chamada para o novo método (ainda em ambiente de teste) é: 

http://serverofi5.bireme.br:8180/SDService/SDService?adhocSimilarDocs= &lt;texto para se procurar documentos similares&gt;

Por ex, para se procurar por documentos similares contendo o assunto zika e mortalidade, a chamada seria:

http://serverofi5.bireme.br:8180/SDService/SDService?adhocSimilarDocs=zika%20mortalidade

**Comment by wilsonmoura** [comment]
@heitorbarbieri Ajustes realizados no ambiente de testes. Realizei alguns testes e percebi que exitem documentos que não estão recuperando similares. Analisando um pouco mais, constatei que os similares não eram recuperados nesses documentos por conta de alguns caracteres, seja no título do respectivo documento ou no corpo do XML retornado com a lista dos similares. Talvez esteja faltando nesse novo método algum processo de normalização de caracteres, pois esse problema não ocorria na forma anterior.

**Comment by wilsonmoura** [comment]
@renatomurasaki O novo método de similaridade para documentos relacionados foi normalizado no ambiente de testes. Favor validar para que possamos aplicar esses ajustes no ambiente de produção.

**Comment by renatomurasaki** [comment]
@wilsonmoura Fiz um teste de documentos similares no ambiente de teste e produção com o mesmo documento: "Abundance and distribution of sylvatic dengue virus vectors in three different land cover types in Sarawak, Malaysian Borneo." O resultado foi diferente no ambiente de testes, comparado com a produção. Em ambos os casos, os documentos similares têm relação com o documento "Abundance and (...)"

**Comment by wilsonmoura** [comment]
Novos testes foram realizados utilizando o novo método de similaridade e os resultados foram normalizados.
