### ISSUE TITLE
Armazenar ranking de similaridade que vem do serviço SimilarDocs

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/plat-serv-bvs#155]
De qualquer forma, o SimilarDocs já retorna os documentos ordenados pelo mais similar, sendo estes armazenados na Minha BVS respeitando a mesma ordem.

**Comment by wilsonmoura** [comment]
Relacionado com bireme/SimilarDocs#12

**Comment by wilsonmoura** [comment]
Resolvido em #163

**Comment by wilsonmoura** [comment]
Os documentos do SimilarDocs são organizados por similaridade e data. Sendo assim, a ordem dos mesmos é armazenada junto ao cache da Minha BVS.
