### ISSUE TITLE
Ajustar prioridade de escolha do idioma dos títulos dos documentos recuperados via SimilarDocs

### ISSUE THREAD

**Issue by wilsonmoura** [bireme/plat-serv-bvs#162]

**Comment by wilsonmoura** [comment]
Ajustar prioridade na seguinte ordem:

1. Tag `ti_<idioma da interface>`
2. Tag `ti_en`
3. Tag `ti_es`
4. Tag `ti_pt`
5. Tag `ti`
6. Tag `ti_<tag la>`
7. Qualquer tag com prefixo `ti_`

**Comment by renatomurasaki** [comment]
@wilsonmoura , considerando que a maioria dos usuários vem do Brasil, não seria melhor alterar a prioridade do idioma para:

1. Tag ti_<idioma da interface>
2. Tag ti_pt
3. Tag ti_es
4. Tag ti_en
5. Tag ti
6. Tag ti_<tag la>
7. Qualquer tag com prefixo ti_
