### ISSUE TITLE
Definir os componentes da página pública das coleções

### ISSUE THREAD

**Issue by wilsonmoura** [bireme/plat-serv-bvs#166]
Exibir na página:
- Informações no cabeçalho (nome de usuário, nome da coleção, etc)
- Recurso para compartilhamento em redes sociais
- Mensagem com metadados da coleção (quem criou, quando criou, quando atualizou, etc)
- Rótulo "Minha BVS", nome do usuário e nome da coleção no título da página (ex. Minha BVS - Renato Murasaki - Nome da coleção (coleção compartilhada))

**Comment by wilsonmoura** [comment]
As informações de criação e atualização não estão presentes na tabela das coleções. Essa tarefa será implementada em #168

**Comment by wilsonmoura** [comment]
Proposta inicial: http://platserv2.teste.bvsalud.org/pt/d2lsc29uLm1vdXJh/4579

**Comment by wilsonmoura** [comment]
Levantamentos feitos por @sousajul e @pintoros:
- Modificar assunto/título nos meios de compartilhamento
- Exibir link para a área de inscrição na Minha BVS
- Alterar ordem dos ícones de compartilhamento

**Comment by wilsonmoura** [comment]
Tags com as informações de compartilhamento:
- Título
- Descrição
- Link

**Comment by wilsonmoura** [comment]
@sousajul @pintoros Estamos no aguardo das sugestões para as tags de informação de compartilhamento, ordem dos ícones das redes sociais e mensagem que acompanha o link que remete para a área de inscrição da Minha BVS.

**Comment by pintoros** [comment]
Sugiro incluir na descrição a seguinte informação:
Coleção disponível na Minha BVS (Minha BVS com link para aplicação)

**Comment by pintoros** [comment]
Quanto a ordem dos icones para redes sociais, sugiro deixar para o final os menos utilizados como Twitter
