### ISSUE TITLE
Adicionar na página de autenticação os videos do curso de capacitação publicado no youtube

### ISSUE THREAD

**Issue by marcoslmori** [bireme/plat-serv-bvs#167]
![image](https://user-images.githubusercontent.com/10047460/32187325-da99a0ae-bd8b-11e7-8cc6-06e531de2b5a.png)

PT
Capacitação sobre os serviços personalizados - Minha BVS - 26/09/2017
https://www.youtube.com/watch?v=5lcfH3YDtBM

ES/EN
Capacitación sobre los servicios personalizados - Mi -  BVS 25/09/2017
https://www.youtube.com/watch?v=FV8g4k5iTs8&t=12s

Consultar Juliana Sousa para identificar o posicionamento e o tipo de publicação

**Comment by sousajul** [comment]
Mori, minha sugestão é incluir um ícone do youtube e linkar para a playlist criada para o Minha BVS de acordo com o idioma da interface do serviço. Assim aumentamos a oferta para o usuário ao invés de linkar para um vídeo em específico. Até porque com o passar do tempo a capacitação está desatualizada devido a incorporação de novas funcionalidades, etc.

Se concordarem, sugiro que o ícone do youtube seja inserido do lado esquerdo abaixo do texto saiba mais, vide anexo.

![image](https://user-images.githubusercontent.com/13439949/32192148-7758369a-bd9a-11e7-8cea-8837900ca263.png)

**Comment by wilsonmoura** [comment]
@sousajul Favor verificar no ambiente de testes se os links adicionados no ícone do YouTube estão corretos.
