### ISSUE TITLE
Função similares não retorna documentos

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/plat-serv-bvs#172]
Ao clicar no link similares, de qualquer documento da minha BVS, seja em Documentos Favoritos ou Temas de Interesse, não retorna qualquer documento. A mensagem apresentada é 

![image](https://user-images.githubusercontent.com/1226218/34613038-667e0eb4-f213-11e7-8c75-96daa595d81d.png)

O serviço http://similardocs.bireme.org/SDService?psId=&getSimDocs= está funcionando corretamente.

**Comment by wilsonmoura** [comment]
@renatomurasaki No arquivo de configuração da Minha BVS, faltou incluir um novo parâmetro com a URL de requisição do novo método de similaridade. O ajuste no ambiente de produção já foi realizado. Favor validar.

**Comment by renatomurasaki** [comment]
@wilsonmoura voltou a funcionar. Verificar procedimento para evitar que a falta desse parâmetro ocorra novamente. Percebi um aumento no tempo de resposta do serviço.
