### ISSUE TITLE
A tabela directories não está registrando as coleções que foram compartilhadas

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/plat-serv-bvs#173]
@wilsonmoura qual ação provoca atualização do campo public?

Simulei compartilhamento de uma das minhas coleções e o registro não foi atualizado nesta tabela.

**Comment by wilsonmoura** [comment]
@renatomurasaki Esse campo fazia parte da modelagem antiga. Não sei em qual função era utilizado. Por isso decidi manter. Mas não está sendo usado no contexto atual. O que define se uma coleção está pública ou não é um parâmetro presente na URL de compartilhamento da coleção.

**Comment by renatomurasaki** [comment]
@wilsonmoura Precisamos monitorar a quantidade de coleções compartilhadas ou que supostamente foram compartilhadas. O que você acha de registrar o evento de clic no link Compartilhar Coleção? Poderíamos colocar como flag boolean no campo public?

**Comment by wilsonmoura** [comment]
@renatomurasaki Assim como em outros links, adicionamos o link de monitoramento de clicks usado no Google Analytics.
