### ISSUE TITLE
RSS: Textos do tour da Minha BVS

### ISSUE THREAD

**Issue by wilsonmoura** [bireme/plat-serv-bvs#180]
Idiomas dos textos: Português, Inglês e Espanhol.

**Comment by wilsonmoura** [comment]
@sousajul Poderia fazer uma proposta/sugestão dos textos que vão explicar esse novo serviço no tour da Minha BVS?

**Comment by sousajul** [comment]
@wilsonmoura segue proposta de textos:

Caixa 1 – RSS
Sugestões
1.	Visualize as últimas atualizações de documentos a partir do RSS de seus portais favoritos
2.	Apresenta de forma prática e automática as últimas atualizações de documentos a partir do RSS de seus portais favoritos

Caixa 2 –  botão adicionar
Clique nesse botão para adicionar uma nova RSS

Caixa 3 – lista
Visualize a listra dos RSS cadastrados.

Dentro de um RSS
Destacar a lista de documentos
Lista dos últimos documentos recuperados via RSS do seu portal favorito. Você pode: editar ou excluir um RSS, adicionar um novo RSS.
