### ISSUE TITLE
Autenticação no Google não funciona no app

### ISSUE THREAD

**Issue by wilsonmoura** [bireme/plat-serv-bvs#193]

**Comment by wilsonmoura** [comment]
Os recursos nativos do site [gonative.io](https://gonative.io/) não resolvem esse problema. Existem alguns [exemplos](https://gonative.io/examples) de apps criados com o [gonative.oi](https://gonative.io/). A maioria desses apps não possui autenticação com o Google. Nos casos que possuem essa opção de autenticação, também não funciona. Temos que avaliar melhor esse problema, tendo em vista que a maioria dos usuários da Minha BVS utilizam o Google como opção de autenticação.

**Comment by renatomurasaki** [comment]
Tentemos mudar o useragent, conforme identificado nas pesquisas realizadas:

https://stackoverflow.com/questions/40591090/403-error-thats-an-error-error-disallowed-useragent
https://www.youtube.com/watch?v=oh3ZHxKYEf8
https://developers.googleblog.com/2016/08/modernizing-oauth-interactions-in-native-apps.html
https://www.theregister.co.uk/2016/08/23/google_to_block_web_views_from_using_its_oauth/

**Comment by renatomurasaki** [comment]
Caso não consiga usar o Google Accounts, teremos que mudar de framework, pois cerca de 40% dos usuários acessam o MinhaBVS via Google Accounts.

**Comment by wilsonmoura** [comment]
Entrei em contato com a equipe do GoNative.io para ver se eles tinham uma solução para o problema de autenticação no Google Accounts. Segui as recomendações deles e a autenticação funcionou! Para a versão Android foi tranquilo, mas para a versão iOS tem que baixar o código e editar o arquivo de configuração (appConfig.json).
