### ISSUE TITLE
Criar evento do Google Analytics para o botão Pesquisar da Caixa de busca da BVS dentro do MinhaBVS

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/plat-serv-bvs#198]
A taxa de rejeição da Minha BVS é mais de 70%. Tenho a suspeita que seja por causa da caixa de busca que remete o usuário para a pesquisa da BVS. Infelizmente não encontrei uma forma no Google Analytics de demonstrar isso por meio dos eventos.

**Comment by wilsonmoura** [comment]
Ajuste realizado no ambiente de testes da seguinte forma:

Category: My VHL
Action: VHL Search Bar
Label: Termo/Query aplicado na pesquisa

@renatomurasaki Favor verificar resultado desse ajuste no Google Analytics.

**Comment by renatomurasaki** [comment]
@wilsonmoura está ok, conforme testes com GA.
