### ISSUE TITLE
Mellhorias no histórico de busca

### ISSUE THREAD

**Issue by marcoslmori** [bireme/plat-serv-bvs#201]
Sugestão enviado por uma usuário do sistema. 

"Bom dia, Em Minha BVS, no histórico de busca, poderia inserir "editar pesquisa", caso aconteça de errar um operador boleano ou termo, permite alterar/corrigir e fazer a pesquisa correta. Ainda no histórico de busca quando estou em outras páginas, quando eu clico em remover uma pesquisa, ele sempre volta na primeira página. Por exemplo, estou organizando as pesquisas na 3ª página; quando clico em remover a pesquisa (na página 3) ele vai para a 1ª página. Aí tem que ficar voltando na página em que estava. O ideal seria ficar na página em que está organizando o histórico"

**Comment by wilsonmoura** [comment]
Para armazenar as pesquisa na Minha BVS, utilizamos o MongoDB, um software de banco de dados. No MongoDB, configuramos o armazenamento da base com tamanho fixo, ou seja, ao atingir o tamanho fixo pré-definido, os registros antigos vão sendo deletados automaticamente da base. Essa característica do MongoDB não pode ser modificada. Além disso, esse tipo de configuração não permite atualização dos registros.

Com relação a paginação do histórico de pesquisas, criamos a issue #203 para resolver esse comportamento.

**Comment by wilsonmoura** [comment]
Resolvido em 4da37bd4c55b2422fa3d9c6dec071c9b83b7fa74
