### ISSUE TITLE
No serviço Minhas Publicações, incluir ícone nas ações "Citado por" e "Artigos Relacionados"

### ISSUE THREAD

**Issue by wilsonmoura** [bireme/plat-serv-bvs#217]

**Comment by riccastros1979** [comment]
Seguem ícones para as funcionalidades solicitadas.

![citado](https://user-images.githubusercontent.com/1419651/51485928-73f88200-1d86-11e9-80b4-74c7c29f80df.gif)
![relacionados](https://user-images.githubusercontent.com/1419651/51485929-74911880-1d86-11e9-8ecd-379be4b35c0c.gif)
