### ISSUE TITLE
Incluir variável/parâmetro nas chamadas ao iAHx para identificar ações provenientes de usuário da MinhaBVS

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/plat-serv-bvs#221]
Objetivo é identificar os acessos vindos do MinhaBVS no log do iAHx

**Comment by viniciusandrade** [comment]
Referência para avaliação:
https://support.google.com/analytics/answer/3123666?hl=en

**Comment by renatomurasaki** [comment]
`ga('set', 'userId', 'USER_ID'); // Set the user ID using signed-in user_id.`

**Comment by renatomurasaki** [comment]
Essa implementação com ga() é "simples" dentro do site da MinhaBVS. Entretanto, para dentro do iAHx, o acesso que vem da MinhaBVS precisa persistir o valor do User-ID. @wilsonmoura converse com o @viniciusandrade sobre esse impacto no iAHx.
