### ISSUE TITLE
Sugestão de alterar ícone "Combinar" do Histórico de Buscas na BVS

### ISSUE THREAD

**Issue by sousajul** [bireme/plat-serv-bvs#263]
O ícone atual (embora esteja na cor azul) me remete um X que é de exclusão, sugiro analisar nas bibliotecas de ícones e padrões da internet um ícone que melhor represente a ação combinar. Algumas ideias:

![image](https://user-images.githubusercontent.com/13439949/68310256-76666700-008e-11ea-847f-424d43e89e19.png)

**Comment by wilsonmoura** [comment]
@sousajul O modelo do ícone segue o padrão da biblioteca que estamos usando para exibir ícones na MinhaBVS (https://materializecss.com/icons.html). Houve uma pesquisa dentro dessa biblioteca e não encontramos outro ícone que se aproximasse ainda mais da função "combinar" além do ícone já existente.
