### ISSUE TITLE
Adicionar comentário na página de pesquisa de opinião da nova interface.

### ISSUE THREAD

**Issue by heitorbarbieri** [bireme/plat-serv-bvs#268]
Sugiro a inclusão de um rodapé na página de opinião, lembrando o usuário que se ele quiser ampliar suas opiniões sobre o produto, pode fazê-lo pressionando o botão do usuário no canto direito superior e depois no ítem de menu "Enviar Comentário".

**Comment by wilsonmoura** [comment]
As funções **Enviar comentário** e **Reportar erro** foram atualizadas para acessar o novo ambiente de contato baseado no LiveZilla.
