### ISSUE TITLE
Notificações por e-mail e alertas no dashboard de novos registros nos perfis criados na Plataforma de Serviços

### ISSUE THREAD

**Issue by wilsonmoura** [bireme/plat-serv-bvs#28]

**Comment by wilsonmoura** [comment]
Ações definidas:
- Duplicar o serviço do SimilarDocs com índice somente de novos documentos.
- Desenvolver serviço de alertas da Minha BVS para identificar se há documentos novos associados aos perfis dos usuários
- Criar a infraestrutura para envio em massa de e-mails com a alerta de novos documentos, informando título e link
- Possibilitar ao usuário a opção de cancelamento do envio de alertas

**Comment by renatomurasaki** [comment]
Este issue será tratado como um projeto a parte, disponível em https://github.com/bireme/my-vhl-alerts
