### ISSUE TITLE
Erro ao tentar recuperar a senha

### ISSUE THREAD

**Issue by barrosjo** [bireme/plat-serv-bvs#281]
Ao tentar recuperar senha aparece a seguinte mensagem de erro:

ERRO: Não foi possível gerar uma nova senha.

e não chega e-mail de recuperação

![MinhaBVS_-_Esqueci_minha_senha_-_2021-12-07_15 10 03](https://user-images.githubusercontent.com/19578003/145083604-a7d244c8-34b5-45c0-9810-ad3c3b8e5b22.png)

**Comment by wilsonmoura** [comment]
Usuário identificado no sistema com origem no serviço BIREME Accounts.

**Comment by barrosjo** [comment]
Não entrou com usuário e senha do BIREME Accounts. Diz que usuário ou senha inválidos.

**Comment by wilsonmoura** [comment]
@barrosjo favor checar os dados corretos desse usuário com algum administrador do BIREME Accounts. Lembrando que, nesse caso, ao invés de usar o próprio e-mail, o login deve ser feito usando o nome de usuário que foi cadastrado no BIREME Accounts.

**Comment by wilsonmoura** [comment]
@barrosjo favor checar os dados corretos desse usuário com algum administrador do BIREME Accounts. Lembrando que, nesse caso, ao invés de usar o próprio e-mail, o login deve ser feito com o nome de usuário que foi cadastrado no BIREME Accounts.
