### ISSUE TITLE
Analisar a implementação o código GA-4 na instancia platserv.bvsalud.org APP

### ISSUE THREAD

**Issue by marcoslmori** [bireme/plat-serv-bvs#287]
Analisar a implementação o código GA-4 na instancia platserv.bvsalud.org APP

Código cadastrado em: https://paho.sharepoint.com/:x:/s/BIR/EVzX0jtquElLhFx_jU--UdQBQg1kS3eDzXC7QhMIN5Bq4g?email=morimarc%40paho.org&e=4%3Atv0Swq&at=9&CID=5487f9bd-3996-c1fa-529b-56b54b77a3a5

**Comment by wilsonmoura** [comment]
@marcoslmori fizemos ajustes para que ambos os códigos (GAU e GA4) possam ser usados. No arquivo de configurações, basta colocar os códigos na respectiva variável (GOOGLE_ANALYTICS ou APP_GOOGLE_ANALYTICS). Favor atualizar o repositório e validar.
