### ISSUE TITLE
Cadastro de Novo Usuário / Erro para geração da senha

### ISSUE THREAD

**Issue by alvesmarilda** [bireme/plat-serv-bvs#292]
De: Alves, Marilda Perez (BIR) <alvesma@paho.org>
Enviado: quarta-feira, 27 de setembro de 2023 13:50
Para: Moura, Wilson Silva (BIR) <mourawil@paho.org>
Cc: Mori, Marcos (BIR) <morimarc@paho.org>; Mota, Jefferson da Justa (BIR) <motaje@paho.org>; Silva, Carlos Roberto da (BIR) <silvaca@paho.org>
Assunto: Problemas Minha BVS / Novo usuário e recuperação de senha
 
Wilson,  Boa Tarde!

Por favor verificar o problema em relação a novo usuário e recuperação de senha no serviço Minha BVS. 

Recebemos mensagem de usuário no Livezilla e fizemos testes para verificação a seguir:

1) Opção Novo Usuário:

jefjusta@gmail.com

Não recebe mensagem sobre o cadastro (caixa de entrada/spam)

Quando utiliza a opção "Esqueci minha senha"

![image](https://github.com/bireme/plat-serv-bvs/assets/38661168/8cf30f1e-38f2-4b03-b11a-b5621683deae)

Recebe a mensagem:

![image](https://github.com/bireme/plat-serv-bvs/assets/38661168/9ca1863e-6004-4de1-9097-a0760cc6434d)

"Não consegue gerar a nova senha."

![image](https://github.com/bireme/plat-serv-bvs/assets/38661168/1c87227c-21a5-4e52-878f-096451a45d91)

2) Validação de cadastro: carlos11lx321silva@gmail.com

![image](https://github.com/bireme/plat-serv-bvs/assets/38661168/e15f3973-2860-4537-b16b-e7b6700e1a2c)

Não recebe a mensagem.

Opção "Esqueci Minha Senha" (Erro):

![image](https://github.com/bireme/plat-serv-bvs/assets/38661168/580340c4-0fb7-4554-b5ae-258e61684163)

![image](https://github.com/bireme/plat-serv-bvs/assets/38661168/0f7f9948-eb1f-431c-86fb-8995b62c99c9)

Obrigada!

**Comment by wilsonmoura** [comment]
@alvesmarilda o serviço que implementamos para realizar a autenticação padrão (LDAP) será descontinuado. Sendo assim, vamos analisar uma outra forma para substituir o mecanismo atual responsável pela autenticação padrão do sistema. Informo também que, para evitar problemas futuros, vamos ajustar o sistema e desativar o registro de usuários até que esse novo mecanismo de autenticação esteja totalmente pronto e implementado.

**Comment by wilsonmoura** [comment]
@alvesmarilda Conforme solicitado, desativamos temporariamente o módulo de registro de usuários (#294) até finalizarmos a nova camada de autenticação padrão do sistema.

**Comment by wilsonmoura** [comment]
@alvesmarilda finalizamos os ajustes na camada de autenticação da plataforma MiBVS. Sendo assim, o login e o cadastro de usuários já estão liberados novamente.

**NOTA:** ao tentar realizar o login, na grande maioria dos casos, o sistema pode mostrar a mensagem abaixo:

![screenshot-platserv local bvsalud org-2023 11 21-17_56_13](https://github.com/bireme/plat-serv-bvs/assets/3779520/17ba45a4-edee-4789-8ec8-7a240f8c6f60)

Nesse caso, basta o usuário seguir a orientação dessa mensagem e gerar uma nova senha para ter acesso ao sistema.

**Comment by alvesmarilda** [comment]
Obrigada!

Abs
