### ISSUE TITLE
Gerar ícones do app em alta resolução (1024px)

### ISSUE THREAD

**Issue by wilsonmoura** [bireme/plat-serv-bvs#298]
Logo MiBVS:
![Logo MiBVS](https://raw.githubusercontent.com/bireme/plat-serv-bvs/master/client/images/myvhl/logo-mb-hexa.png)

Logo MiBVS com fundo branco:
![Logo MiBVS Branco](https://raw.githubusercontent.com/bireme/plat-serv-bvs/master/client/images/myvhl/logo-mb-hexa-branco.png)

**Comment by marcioalvessilva** [comment]
Segue imagens
![MiBVS-com-fundo](https://github.com/bireme/plat-serv-bvs/assets/48724136/6a92fccb-7e57-4ce2-9293-20e9f854924f)
![MiBVS-sem-fundo](https://github.com/bireme/plat-serv-bvs/assets/48724136/49903f72-ae82-4754-a9d3-46d18840b273)

**Comment by wilsonmoura** [comment]
@marcioalvessilva obrigado!

**Comment by marcioalvessilva** [comment]
![MiBVS-sem-fundo](https://github.com/bireme/plat-serv-bvs/assets/48724136/c887aebe-a205-4e47-816b-31a135736da4)
![MiBVS-com-fundo](https://github.com/bireme/plat-serv-bvs/assets/48724136/0b35b901-543b-4cce-b81f-ceccbdaeeda3)
