### ISSUE TITLE
Gerar screenshots para publicação nas lojas de apps do Google e Apple

### ISSUE THREAD

**Issue by wilsonmoura** [bireme/plat-serv-bvs#299]
Os screenshots atuais ainda são da versão antiga do app MiBVS. Sendo assim, precisamos gerar screenshots da versão mais recente para atualizar nas lojas de apps do Google e Apple.

**Comment by marcioalvessilva** [comment]
Se precisar demais só me avisar

![screenshot 0](https://github.com/bireme/plat-serv-bvs/assets/48724136/fedb7c93-2289-4a8f-aca7-e041b7bfe504)
![screenshot 1](https://github.com/bireme/plat-serv-bvs/assets/48724136/e1f61404-2a2f-473b-9812-a06f59d92ef2)
![screenshot 2](https://github.com/bireme/plat-serv-bvs/assets/48724136/cd74661a-6244-43c3-8f82-6a13a77a344f)
![screenshot 3](https://github.com/bireme/plat-serv-bvs/assets/48724136/66cf1cb4-d626-402c-8dda-02cf120ab1b0)
![screenshot 4](https://github.com/bireme/plat-serv-bvs/assets/48724136/30928eb0-0ba6-4538-8a68-95e718bc1546)
![screenshot 5](https://github.com/bireme/plat-serv-bvs/assets/48724136/e4892a3a-ebda-4274-81d6-347207e8b230)
![screenshot -ipad-1](https://github.com/bireme/plat-serv-bvs/assets/48724136/3eb8e346-e1ba-496d-a329-7ea124320e24)
![screenshot -ipad-2](https://github.com/bireme/plat-serv-bvs/assets/48724136/5c94b2ea-ca68-4183-bf5c-31b54c89a8fd)
![screenshot -ipad-3](https://github.com/bireme/plat-serv-bvs/assets/48724136/5a45b5e2-9cd3-4a58-9719-ada1e6b5d0e5)

**Comment by wilsonmoura** [comment]
@marcioalvessilva conseguimos enviar as imagens para iPad, mas tivemos problemas com as imagens para celular. Favor ajustar as imagens para celular de acordo com as regras da Apple:

<img width="544" alt="Captura de Tela 2024-04-14 às 20 05 44" src="https://github.com/bireme/plat-serv-bvs/assets/3779520/cf9a266c-babf-47f9-bb23-fddc717edc3e">

**Comment by marcioalvessilva** [comment]
Medidas 1290 x 2796

![screenshot-5](https://github.com/bireme/plat-serv-bvs/assets/48724136/07d42224-9b2b-420a-9d12-eed8ff63806f)
![screenshot-0](https://github.com/bireme/plat-serv-bvs/assets/48724136/3a728fa3-5498-404f-9034-a015694ed77c)
![screenshot-1](https://github.com/bireme/plat-serv-bvs/assets/48724136/29f6b6fc-1577-4d1c-a3d7-813a81d8c26a)
![screenshot-2](https://github.com/bireme/plat-serv-bvs/assets/48724136/bc4a4c8f-f456-44ba-9ffc-767a7a3faea8)
![screenshot-3](https://github.com/bireme/plat-serv-bvs/assets/48724136/6e4fb247-f334-4e75-8ec2-2607491bb25c)
![screenshot-4](https://github.com/bireme/plat-serv-bvs/assets/48724136/cfe0c588-e8f8-47c3-a7df-38fe671bf527)

**Comment by wilsonmoura** [comment]
@marcioalvessilva por favor, providenciar as imagens também nos padrões abaixo:

<img width="548" alt="Captura de Tela 2024-06-16 às 21 42 24" src="https://github.com/bireme/plat-serv-bvs/assets/3779520/86cc428c-62fd-4381-a42c-1745ecbe8542">

**Comment by marcioalvessilva** [comment]
[imagens.zip](https://github.com/user-attachments/files/15928048/imagens.zip)
Segue imagens

**Comment by wilsonmoura** [comment]
@marcioalvessilva as imagens que foram enviadas são do app e-BlueInfo. Favor enviar as imagens para o app MiBVS.

**Comment by marcioalvessilva** [comment]
Desculpe falta de atenção vou enviar hoje

**Comment by marcioalvessilva** [comment]
Segue em pasta zipada imagem 1242 x 2208
[1242x2208.zip](https://github.com/user-attachments/files/15959647/1242x2208.zip)

**Comment by wilsonmoura** [comment]
@marcioalvessilva obrigado pelo apoio!
