### ISSUE TITLE
Mudança na visualização do histórico de buscas na BVS

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/plat-serv-bvs#49]
A coluna atual de Filtro mostrará o nome da instância BVS de origem, com o label BVS. Será criada uma nova coluna contendo o filtro, com o label Filtro. O filtro instance não deve ser utilizado na combinação de buscas.

Limitar a visualização dos conteúdos da coluna Query, mostrando reticencias para que o usuário possa expandi-la.

**Comment by wilsonmoura** [comment]
Em vez de acrescentar uma coluna com o nome do site de origem, vamos enviar essa informação via plugin BVS, retirando esse dado do link informado no widget de login nos Serviços Personalizados.

**Comment by wilsonmoura** [comment]
Recuperar o nome da instância iAHx informada no widget do plug-in BVS (Site de Origem) para mostrar na opção "Exibir no" do botão Exibir.

Exemplo:

pesquisa.bvsalud.org/brasil - deve extrair `brasil`, mandar para a plataforma de serviço que fará a tradução para BVS Brasil e mostrará no botão Exibir: BVS Brasil e Portal Regional da BVS.
