### ISSUE TITLE
Corrigir texto "Saiba sua faixa etária e idioma" em permissões ao acessar pelo Google

### ISSUE THREAD

**Issue by sousajul** [bireme/plat-serv-bvs#52]
Corrigir o texto "Saiba sua faixa etária e idioma" para "**Saber**..." na tela em que o serviço solicita algumas permissões.

![image](https://cloud.githubusercontent.com/assets/13439949/25235398/66d555f4-25bb-11e7-8a6f-536d8ad4e72a.png)

**Comment by wilsonmoura** [comment]
@sousajul Essa informação vem da API do Google. Sendo assim, não é possível alterar essa mensagem.

**Comment by sousajul** [comment]
Ok.
