### ISSUE TITLE
Verificar o fluxo de navegação do Serviço Personalizado

### ISSUE THREAD

**Issue by sousajul** [bireme/plat-serv-bvs#53]
Após realizar as alterações em "Editar meu perfil" e clicar em atualizar, não está claro como faço para voltar para a Home do  Dashboard. Após algumas tentativas descobri que tenho que clicar em Dashboard para depois clicar em Home.

Sugestão:
- Ao clicar em atualizar, poderia remeter automaticamente para a home ou
- Deixar o link da Home mais visível.

**Comment by wilsonmoura** [comment]
@sousajul vamos ajustar para que o menu completo sempre fique visível.

**Comment by wilsonmoura** [comment]
@sousajul Os ajustes foram realizados. Favor validar.

**Comment by sousajul** [comment]
Neste caso, a label home foi alterada para Visão Geral. Ok deixando o menu fixo acredito que ajuda na navegação.
