### ISSUE TITLE
Alterar a label "Meus perfis de interesse"

### ISSUE THREAD

**Issue by sousajul** [bireme/plat-serv-bvs#54]
Ao realizar os testes, a label "Meus perfis de interesse" ficou um pouco confusa, no meu ponto de vista, por alguns instantes cheguei a confundir com o item "Editar perfil" (perfil do usuário).
Sugestão:
- Alterar a label para, por exemplo, "Minhas áreas de interesse", "Meus temas de interesse", "Áreas de atuação de interesse"...ou
- Incluir help no campo explicando o que é "Meus perfis de interesse"

**Comment by wilsonmoura** [comment]
@sousajul vamos revisar os rótulos e a ordem do menu principal. Seguem sugestões:

- Dashboard >> Meus Conteúdos
- Home >> Visão Geral
- Documentos Favoritos
- Meus Perfis de Interesse >> Temas de Interesse
- Documentos Relacionados
- Histórico de Buscas na BVS
- Meus Links >> Links Favoritos
- ORCID - Minhas Publicações

**Comment by wilsonmoura** [comment]
@sousajul Os ajustes de labels foram realizados. Favor validar.

**Comment by sousajul** [comment]
Ok.
