### ISSUE TITLE
Palavras-chaves 

### ISSUE THREAD

**Issue by sousajul** [bireme/plat-serv-bvs#55]
Em "Meus perfis de interesse" o campo Palavras-chave indica que as mesmas devem ser separadas por espaço. Mas, caso eu tenha uma palavra-chave composta como o sistema reconhece? Por ex: Experiencia do Usuário. Ele entende palavra por palavra?

![image](https://cloud.githubusercontent.com/assets/13439949/25236813/3529de2c-25bf-11e7-9537-e84d0ee51f31.png)

**Comment by wilsonmoura** [comment]
@sousajul estamos pensando em ajustar a mensagem de ajuda desse campo para "Os termos devem ser separados por vírgula". Neste caso, o rótulo "Palavras-chave" desse campo também deve ser alterado? Se sim, por favor informe sua sugestão.

**Comment by wilsonmoura** [comment]
@sousajul Os ajustes foram realizados conforme último comentário. Favor validar.

**Comment by sousajul** [comment]
@wilsonmoura ficou mais claro o texto de ajuda e não gera dúvidas. Quanto ao rótulo, acredito estar Ok.
