### ISSUE TITLE
Em "Meus perfis de Interesse" ao clicar em [ver todos] não mostra todos os perfis criados

### ISSUE THREAD

**Issue by sousajul** [bireme/plat-serv-bvs#56]
Em "Meus perfis de Interesse" ao clicar em [ver todos] não mostra todos os perfis criados. Penso que os perfis criados poderiam aparecer listados do lado esquerdo e não seria necessário manter o item Perfis do lado direito.

![image](https://cloud.githubusercontent.com/assets/13439949/25237589/75e1ccf2-25c1-11e7-80e3-02b3ba6f5944.png)

**Comment by wilsonmoura** [comment]
@sousajul Ao criar o primeiro perfil de interesse, o mesmo será definido como padrão, mantendo-se a arquitetura da página.

**Comment by wilsonmoura** [comment]
@sousajul Os ajustes foram realizados conforme último comentário. Favor validar.

**Comment by sousajul** [comment]
@wilsonmoura Ok.
