### ISSUE TITLE
Gerar lista de usuários inativos da Plataforma de Serviços para remoção do AD

### ISSUE THREAD

**Issue by wilsonmoura** [bireme/plat-serv-bvs#66]

**Comment by renatomurasaki** [comment]
Dos 169.671 usuários cadastrados, 90.822 usuários nunca criaram um perfil de interesse ou adicionaram um documento favorito. Estamos classificando-os como inativos, os quais serão eliminados do serviço. Abaixo query que identifica os mesmos.

`SELECT COUNT(*) 
FROM <tabela de usuarios> AS u LEFT JOIN <tabela dos favoritos> AS s ON u.sysUID = s.sysUID  LEFT JOIN <tabela dos perfis> AS p ON u.sysUID = p.sysUID 
WHERE (s.sysUID IS NULL AND p.sysUID IS NULL)`

**Comment by wilsonmoura** [comment]
A lista de usuários que devem ser removidos do AD foi enviada ao Marco Miacci via e-mail.
