### ISSUE TITLE
Verificar a frase de "aviso" ao adicionar um documento aos favoritos em Temas de Interesse

### ISSUE THREAD

**Issue by sousajul** [bireme/plat-serv-bvs#72]
Em temas de interesse, ao adicionar um registro em favoritos, informa que o documento foi adicionado à coleção. Mas em nenhum momento o sistema fala de coleção. A frase poderia ser: "documento adicionado em documentos favoritos"

Sugestão: A label "adicionar aos favoritos" pode gerar confusão de qual favoritos, documentos ou links, por mais que eu esteja adicionando um documento e não um link, poderia se deixar mais claro. 

![image](https://cloud.githubusercontent.com/assets/13439949/26128207/ff32238a-3a61-11e7-9901-dc7eca0cf70e.png)

**Comment by wilsonmoura** [comment]
Desconsiderar esta issue, incluido no issue #75

**Comment by wilsonmoura** [comment]
@sousajul Essa issue foi resolvida em #75. Favor validar.
