### ISSUE TITLE
Ranking

### ISSUE THREAD

**Issue by sousajul** [bireme/plat-serv-bvs#73]
Como funciona o sistema de Ranking? Ao adicionar um documento ou um link o ranking padrão já mostra 3 estrelas. Ao clicar em "Visualizar Lista por: Meu ranking", mostra tudo, pois não consigo incluir o ranking.

**Comment by wilsonmoura** [comment]
Alterar a borda das estrelinhas do ranking para cinza.

**Comment by wilsonmoura** [comment]
@sousajul Os ajustes foram realizados. Favor validar.
