### ISSUE TITLE
Revisar as labels do item "Documentos Favoritos"

### ISSUE THREAD

**Issue by sousajul** [bireme/plat-serv-bvs#74]
No item documentos favoritos revisar as labels Minhas Coleções, Adicionar Coleção e Pasta de Entrada. 

Ao clicar em Adicionar coleção, a janela que abre mostra a opção de editar pasta.

![image](https://cloud.githubusercontent.com/assets/13439949/26129236/d3a217e4-3a65-11e7-80ea-b7344677f665.png)

![image](https://cloud.githubusercontent.com/assets/13439949/26129646/791d8d92-3a67-11e7-93bf-9c4a35e4fe9f.png)

**Comment by wilsonmoura** [comment]
Alterar também o rótulo "Pasta de Entrada" para "Caixa de Entrada".

**Comment by wilsonmoura** [comment]
@sousajul Os ajustes foram realizados. Favor validar.
