### ISSUE TITLE
Analisar comportamento das opções do item "Temas de interesse"

### ISSUE THREAD

**Issue by sousajul** [bireme/plat-serv-bvs#75]
No item "Temas de Interesse" analisar os seguintes comportamentos:
1. Ao clicar em "Adicionar aos favoritos", abrir uma opção de escolher qual a "coleção" que eu quero adicionar o documento, sem que seja necessário ir para Documentos favoritos > pasta de entrada > escolher o documento > mover para > escolher a coleção.

2. Ao adicionar um documento várias vezes aos favoritos, o sistema não apresenta nenhuma mensagem informando que o documentos já foi adicionado à "coleção", o sistema poderia:
- informar que o documento já foi adicionado, ou 
- retirar aquele documento da lista uma vez que ele já foi adicionado.

3. Na lista de documentos que o sistema gera, acredito ser intuitivo que ao clicar no título, será direcionado ao texto completo, no entanto, em outros itens como, por exemplo, "Documentos Favoritos" há o
 botão "exibir documento" acredito ser desnecessário uma vez que para ir para o texto completo está intuitivo clicar no título, ou incluir este botão em todos os documentos dos itens da plataforma.

**Comment by wilsonmoura** [comment]
@sousajul Os ajustes foram realizados. Favor validar.

**Comment by wilsonmoura** [comment]
Revisar mensagem exibida quando o documento já existe em alguma coleção.

Mensagem: "Este documento já existe na coleção XXX."

**Comment by wilsonmoura** [comment]
Remover foco após adicionar um documento aos favoritos.

**Comment by wilsonmoura** [comment]
Resolvido em 8c44426507479ebda879897bb578053b5afbafe0
