### ISSUE TITLE
Proposta de arquitetura da área de login de usuários

### ISSUE THREAD

**Issue by wilsonmoura** [bireme/plat-serv-bvs#85]

**Comment by sousajul** [comment]
Proposta desenvolvida e disponível em: http://omka5d.axshare.com para análise, cometários e validação de toda a equipe.

**Proposta para texto de apresentação:**

O serviço Minha BVS registra as informações dos usuários e as preferências de pesquisa nas bases de dados da Rede BVS para fornecer serviços personalizados aos usuários da BVS.

Isto significa que você poderá:
- Selecionar documentos de interesse
- Criar sua própria coleção
- Acessar documentos relacionados aos temas de seu interesse 
- Guardar o histórico de busca realizadas na BVS por XXXX tempo
- Organizar os links dos seus sites favoritos
- Armazenar suas publicações por meio do ORCID
- Ter um espaço próprio/dashboard para salvar todas as suas preferencias de pesquisa

Visão Geral do Minha BVS
YouTube (link)
Tutorial de uso (link)
Termo de uso e Politica de Privacidade (link)
_____
Benchmarking [NCBI](https://www.ncbi.nlm.nih.gov/account/?back_url=https%3A%2F%2Fwww.ncbi.nlm.nih.gov%2Fpubmed%2F) – Pudmed

**Comment by wilsonmoura** [comment]
Será implementado em #92
