### ISSUE TITLE
Sugestão para tela Cadastro de novo usuário

### ISSUE THREAD

**Issue by sousajul** [bireme/plat-serv-bvs#87]
Poderia diminuir a quantidade de campos a serem preenchidos, os campos Lattes (URL), LinkedIn (URL), ResearchGate (URL), ORCID e ResearcherID poderia ser preenchido quando o usuário editar o perfil.

Os campos País, Titulação e Sexo acredito que vale a pena manter se estas informações forem relevantes para algum tipo de métrica futura.

Na proposta de AI que fiz para esta página de login já tem uma ideia inicial para esta interface.

**Comment by wilsonmoura** [comment]
criado issue #88 para implementação.
