### ISSUE TITLE
Obter mais informação do usuario que se loga com as contas de FB e Google

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/plat-serv-bvs#9]

**Comment by wilsonmoura** [comment]
As informações adicionais são solicitadas via API. Seguem links com informações:

**Facebook**: https://developers.facebook.com/docs/graph-api
**Google**: https://developers.google.com/identity/protocols/googlescopes

Algumas dessas informações são disponibilizadas de acordo com as permissões disponíveis. As permissões adicionais são configuradas da seguinte forma:

**Facebook**: acessar https://developers.facebook.com/, escolher o aplicativo, ir em `Configurações > Revisão do Aplicativo` e enviar o aplicativo para revisão com as permissões desejadas. Após aprovação, adicionar as permissões na variável `fbPermissions` localizada no arquivo `client/connector/facebook/config.php`
**Google**: adicionar as permissões na variável `scopes` localizada no arquivo `client/connector/google/config.php`
