### ISSUE TITLE
Identificar lista de valores para Áreas de Atuação

### ISSUE THREAD

**Issue by wilsonmoura** [bireme/plat-serv-bvs#91]
@sousajul Devem englobar ciências da saúde e outras áreas correlatas.

**Comment by sousajul** [comment]
Seguem alguns links para avaliação
- http://www.cnpq.br/documents/10157/186158/TabeladeAreasdoConhecimento.pdf
- http://fisio.icb.usp.br:4882/posgraduacao/bolsas/capesproex_bolsas/tabela_areas.html
- https://pt.wikipedia.org/wiki/Profissional_da_%C3%A1rea_da_sa%C3%BAde
- http://www.portalsaofrancisco.com.br/categoria/profissoes/page/4
 http://www.capes.gov.br/images/documentos/documentos_diversos_2017/TabelaAreasConhecimento_072012_atualizada_2017_v2.pdf

**Comment by renatomurasaki** [comment]
Considerando a abrangência do serviço em nivel internacional, vamos adotar a tabela do CNPq como referencia apenas no nível de sub-área das grandes áreas do conhecimento:

Referente a Ciências da Saúde:
- Medicina
- Odontologia
- Farmácia
- Enfermagem
- Nutrição
- Saúde Coletiva
- Fonoaudiologia
- Fisioterapia e Terapia Ocupacional
- Educação Física

Ciências Biológicas
- Biologia Geral
- Genética
- Botânica
- Zoologia
- Ecologia
- Morfologia
- Fisiologia
- Bioquímica
- Biofísica
- Farmacologia
- Imunologia
- Microbiologia
- Parasitologia

Ciências Agrárias
- Medicina Veterinária

Ciências sociais aplicadas
- Ciência da Informação

Ciências Humanas
- Psicologia
- Educação

Outros 1:
- Ciências Exatas e da Terra
- Engenharias
- Ciências Agrárias
- Ciências sociais aplicadas
- Ciências Humanas
- Lingüística, Letras e Artes

Outros 2:
- Biomedicina
- Outros

**Comment by sousajul** [comment]
Segue anexo a tradução para espanhol e inglês das áreas do conhecimento com base no DeCS e SciELO.
[traducao-areas-conhecimento.docx](https://github.com/bireme/plat-serv-bvs/files/1201137/traducao-areas-conhecimento.docx)
