### ISSUE TITLE
Incluir foto no perfil

### ISSUE THREAD

**Issue by sousajul** [bireme/plat-serv-bvs#95]
Verificar a possibilidade de incluir foto do perfil quando usuário registra-se na plataforma e não acessa pelas redes sociais. Este campo poderia estar por exemplo no item Perfil.

**Comment by wilsonmoura** [comment]
@sousajul Implementamos essa issue no ambiente de teste. Para a imagem aparecer corretamente, a mesma deve ter os lados iguais. Favor validar.
