### ISSUE TITLE
Textos das mensagens recebidas por email

### ISSUE THREAD

**Issue by sousajul** [bireme/plat-serv-bvs#97]
Ao se registrar no serviço, por meio do link Registrar-se. O sistema envia 2 emails para o usuário,
seguem sugestão de textos:

Email confirmação de registro
**Texto Original:**
Assunto: New Services Platform User: Juliana
De: Services Platform <servplat@bireme.org>
Dear Juliana,
Your new account is set up.
Please click on the link below to confirm your account with the Services Platform.
http://platserv.bvsalud.org/server/pub/userData.php?c=cGxhdHNlcnYuYnZzYWx1ZC5vcmcvY2xpZW50L2NvbnRyb2xsZXIvYXV0aGVudGljYXRpb24=&email=sousajul@paho.org&key=90ff077c3f50a2c174c78849027e7fcf&acao=confirmar
Thanks!

**Sugestão:**
Assunto: **Minha BVS - serviços personalizados: confirmação de registro** 
De: **Minha BVS - serviços personalizados** <servplat@bireme.org>
**Prezada** Juliana,

Você se registrou no serviço personalizado Minha BVS. Clique no link abaixo para confirmar sua conta.

Http://platserv.bvsalud.org/server/pub/userData.php?c=cGxhdHNlcnYuYnZzYWx1ZC5vcmcvY2xpZW50L2NvbnRyb2xsZXIvYXV0aGVudGljYXRpb24=&email=sousajul@paho.org&key=90ff077c3f50a2c174c78849027e7fcf&acao=confirmar

Obrigado!
************************

Email de envio de senha
**Texto Original**
Assunto: New BVS network password
De: Services Platform <servplat@bireme.org>

Texto:
Your new password is: XXXXXXXXX

**Sugestão**
Assunto: **Minha BVS - serviços personalizados: senha**
De: **Minha BVS - serviços personalizados** <servplat@bireme.org>

Texto:
Sua nova senha é: XXXXXXXXX
[Clique aqui](http://platserv2.teste.bvsalud.org/client/controller/authentication) e acesse o serviço Minha BVS.
Obrigado!

**Comment by wilsonmoura** [comment]
@sousajul As mensagens foram ajustadas conforme solicitação. Por limitação do recurso de e-mail, o texto do campo **De** foi modificado, pois não aceita diacríticos e caracteres especiais. Favor validar.

**Comment by wilsonmoura** [comment]
Após reunião com o Dr. Diego, o novo texto enviado por e-mail após registro de usuário será:

**Registro de Usuário**

Assunto: Serviços Personalizados Minha BVS: Confirmação de Registro
De: Minha BVS servplat@bireme.org

<div style="background: url(http://platserv.bvsalud.org/client/images/default/banner_top.png) no-repeat; white-space: nowrap;">
        <img src="http://platserv.bvsalud.org/client/images/default/logo-md-pt.png" style="margin: 10px; vertical-align: middle;" />
        <img src="http://platserv.bvsalud.org/client/images/default/logo-bireme-md-pt.png" style="margin: 10px; vertical-align: middle;" />
</div>

Prezada Juliana,

A BIREME/OPAS/OMS lhe dá as boas-vindas aos Serviços Personalizados Minha BVS.

<a href="http://platserv.bvsalud.org/server/pub/userData.php?c=cGxhdHNlcnYuYnZzYWx1ZC5vcmcvY2xpZW50L2NvbnRyb2xsZXIvYXV0aGVudGljYXRpb24=&email=sousajul@paho.org&key=90ff077c3f50a2c174c78849027e7fcf&acao=confirmar">Clique aqui para confirmar seu registro.</a>

Ao acessar a Minha BVS, você terá a oportunidade de conhecer as funcionalidades desse serviço por meio de um tour virtual. Qualquer dúvida ou problema, <a href="http://feedback.bireme.org/feedback/?application=wp-bvs-plugin&version=1.0&lang=pt">entre em contato conosco.</a>

Se você não solicitou o registro na Minha BVS, por favor <a href="http://feedback.bireme.org/feedback/wp-bvs-plugin?version=1.0&error=1">clique aqui.</a>

Atenciosamente,

Equipe BIREME/OPAS/OMS

**Comment by wilsonmoura** [comment]
**Envio de Senha / Confirmação de Cadastro**

Assunto: Serviços Personalizados Minha BVS: Senha
De: Minha BVS servplat@bireme.org

<div style="background: url(http://platserv.bvsalud.org/client/images/default/banner_top.png) no-repeat; white-space: nowrap;">
        <img src="http://platserv.bvsalud.org/client/images/default/logo-md-pt.png" style="margin: 10px; vertical-align: middle;" />
        <img src="http://platserv.bvsalud.org/client/images/default/logo-bireme-md-pt.png" style="margin: 10px; vertical-align: middle;" />
</div>

Prezada Juliana,

A senha do seu usuário na Minha BVS é: XXXXXXXXX

<a href="http://platserv.bvsalud.org/client/controller/authentication/lang=pt">Clique aqui e acesse os Serviços Personalizados.</a>

Qualquer dúvida ou problema, <a href="http://feedback.bireme.org/feedback/?application=wp-bvs-plugin&version=1.0&lang=pt">entre em contato conosco.</a>

Se você não solicitou o envio de senha, por favor <a href="http://feedback.bireme.org/feedback/wp-bvs-plugin?version=1.0&error=1">clique aqui.</a>

Atenciosamente,

Equipe BIREME/OPAS/OMS

**Comment by wilsonmoura** [comment]
Mensagens revisadas e traduzidas. Pendente implementação do cabeçalho das mensagens.
