### ISSUE TITLE
Termos de Uso e Política de Privacidade

### ISSUE THREAD

**Issue by wilsonmoura** [bireme/plat-serv-bvs#99]

**Comment by renatomurasaki** [comment]
@wilsonmoura Segue o texto em ESPANHOL para os Termos e Condições de Uso dos Sitios e Sistemas Web da BIREME/OPAS.

[TyCREDBIREME-final.pdf](https://github.com/bireme/plat-serv-bvs/files/1222507/TyCREDBIREME-final.pdf)

**Comment by renatomurasaki** [comment]
@wilsonmoura Segue o texto em ESPANHOL para a Política de Privacidade dos Sitios e Sistemas Web da BIREME/OPAS.

[PolíticaPrivacidadBIREME-OPS.pdf](https://github.com/bireme/plat-serv-bvs/files/1225444/PoliticaPrivacidadBIREME-OPS.pdf)

**Comment by wilsonmoura** [comment]
Termos de Uso e Política de Privacidade implementados apenas no idioma espanhol. Aguardando traduções para finalizar tarefa.

**Comment by renatomurasaki** [comment]
@wilsonmoura Seguem as traduções em PORTUGUÊS dos Termos e Condições de Uso e da Política de Privacidade.

[TyCREDBIREME--20170814-port.pdf](https://github.com/bireme/plat-serv-bvs/files/1232275/TyCREDBIREME--20170814-port.pdf)
[Política de Privacidad BIREME-OPS--20170814-port.pdf](https://github.com/bireme/plat-serv-bvs/files/1232273/Politica.de.Privacidad.BIREME-OPS--20170814-port.pdf)

**Comment by wilsonmoura** [comment]
Termos de Uso e Política de Privacidade implementados no idioma português. Aguardando tradução para o idioma inglês.

**Comment by renatomurasaki** [comment]
@wilsonmoura Por favor, atualizar as versões PORTUGUÊS e ESPANHOL da Política de Privacidade que seguem anexo, após revisão de LEG.

PT - [Política de Privacidad BIREME-OPS--20170814-port-v1.pdf](https://github.com/bireme/plat-serv-bvs/files/1246796/Politica.de.Privacidad.BIREME-OPS--20170814-port-v1.pdf)
ES - [Política de Privacidad BIREME-OPS-v1.pdf](https://github.com/bireme/plat-serv-bvs/files/1246797/Politica.de.Privacidad.BIREME-OPS-v1.pdf)

**Comment by renatomurasaki** [comment]
@wilsonmoura Seguem as traduções de ambos documentos para o INGLÊS

[Política de Privacidad BIREME-OPS English.pdf](https://github.com/bireme/plat-serv-bvs/files/1247119/Politica.de.Privacidad.BIREME-OPS.English.pdf)
[TyCREDBIREMEenglish.pdf](https://github.com/bireme/plat-serv-bvs/files/1247120/TyCREDBIREMEenglish.pdf)

**Comment by renatomurasaki** [comment]
@wilsonmoura os links dos Termos e Política de Privacidade em inglês ainda estão apontando para a versão espanhol. Favor asap alterar para as versões traduzidas já disponíveis.

**Comment by wilsonmoura** [comment]
@renatomurasaki Termos de Uso e Política de Privacidade implementados no idioma inglês.

**Comment by wilsonmoura** [comment]
@renatomurasaki Política de Privacidade atualizada nos idiomas espanhol e português.
